Update KEKE-apk.yml

diff --git a/.github/workflows/KEKE-apk.yml b/.github/workflows/KEKE-apk.yml
--- a/.github/workflows/KEKE-apk.yml
+++ b/.github/workflows/KEKE-apk.yml
@@ -11,6 +11,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      # Step 1: 检查输入 APK 文件是否存在
+      - name: Check Input APK File
+        run: |
+          ls -al
+          if [ ! -f 可可影视_3.3.3.apk ]; then
+            echo "Error: Input APK not found!"
+            exit 1
+          fi
+
       # Step 2: 设置 JDK 17
       - name: Set up JDK
         uses: actions/setup-java@v2
@@ -31,6 +40,7 @@ jobs:
       - name: Align APK
         run: |
           zipalign -v 4 可可影视_3.3.3.apk 可可影视_3.3.3-aligned.apk
+          ls -al  # 列出文件以确认对齐后的 APK 是否存在
 
       # Step 6: 使用新的密钥签名
       - name: Sign APK with apksigner
@@ -46,6 +56,7 @@ jobs:
             --out 可可影视_3.3.3-signed.apk \
             --v2-signing-enabled true \
             可可影视_3.3.3-aligned.apk
+          ls -al  # 列出文件以确认签名后的 APK 是否存在
             
       # Step 7: 验证签名后的 APK
       - name: Verify Signed APK
@@ -66,8 +77,8 @@ jobs:
         id: create_release
         uses: softprops/action-gh-release@v1
         with:
-          tag_name: v2.0.1  # 替换为你的版本号
-          name: Release v2.0.1  # 使用 'name' 参数设置发布名称
+          tag_name: v2.0.2  # 替换为你的版本号
+          name: Release v2.0.2  # 使用 'name' 参数设置发布名称
           body: |
             这是一个自动生成的发布版本。
           files: |
